language: java
jdk:
  - openjdk7
  - oraclejdk7

script: "mvn --show-version --errors --batch-mode -Prun-its clean verify -Dinvoker.streamLogs=true"

cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
